spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://logindb.cusnc22ncotq.us-east-1.rds.amazonaws.com:3306/login
        username: root
        password: root1234

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL8Dialect
    